# Generated by Django 3.0.7 on 2020-06-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polling',
            name='django',
        ),
        migrations.RemoveField(
            model_name='polling',
            name='graphql',
        ),
        migrations.RemoveField(
            model_name='polling',
            name='rest',
        ),
        migrations.RemoveField(
            model_name='polling',
            name='soap',
        ),
        migrations.AddField(
            model_name='polling',
            name='django_know',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='django_unknown',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='django_worked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='graphql_know',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='graphql_unknown',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='graphql_worked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='rest_know',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='rest_unknown',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='rest_worked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='soap_know',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='soap_unknown',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='polling',
            name='soap_worked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='DjangoPoll',
        ),
        migrations.DeleteModel(
            name='GraphqlPoll',
        ),
        migrations.DeleteModel(
            name='RestPoll',
        ),
        migrations.DeleteModel(
            name='SoapPoll',
        ),
    ]
